swagger: "2.0"

info:
  version: "1.0.0"
  title: "Himaaus Royalty Project"
  description: "A simple API to learn how to write OpenAPI Specification"

schemes:
  - "http"
host: localhost:3000
basePath: "/api"

